version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: flask_app:tag
    build: ./api
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
    restart: always

  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  react_app:
    container_name: react_app
    image: react_app:tag
    build: ./app
    ports:
      - "3000:3000"
    restart: always

volumes:
  pgdata: {}