name: Github Actions

on:
  push:
    branches:
      - github-actions
  pull_request:
    branches:
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name : run and build the docker-compose file
        run: |
          docker compose up --build -d
          sleep 20
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r ./tests/requirements.txt
      - name : run the tests folder
        run : pytest tests/
      - name : down the docker-compose file
        run: docker compose down